{% set name = "jupysql-plugin" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupysql_plugin-{{ version }}.tar.gz
  sha256: 92e68a9276dcd349cb1b0094b142e05054f9db2a29b541f69a75321986d860a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=1.4.0
    - jupyterlab >=3.4.7,<4.0.0
    - hatch-jupyter-builder
    - hatch-nodejs-version
    - pip
  run:
    - python >=3.7
    - ploomber-core
    - jupyter_server

test:
  imports:
    - jupysql_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ploomber/jupysql-plugin
  summary: Jupyterlab extension for JupySQL
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - edublancas
    - neelasha23
